### ISSUE TITLE
Cannot retrieve a correct property value of an input module

### ISSUE THREAD

**Issue by jacob-an** [LUXROBO/pymodi#102]
* pyMODI version: 0.7.0
* Python version: 3.7
* Operating System: Windows 10

### Description
A single call of getter methods of the input modules does not return the correct state of the module.

### What I Expected
In an initial call of a method of an input module, the module should return the correct property value.

**Comment by jha929** [comment]
Please attach a relevant python script for reproducing the issue.

**Comment by jha929** [comment]
This issue has been addressed recently. The code will be merged in the next version, 0.9.0.
