### ISSUE TITLE
Calling display set_text method raises an error relating to json serialization.

### ISSUE THREAD

**Issue by jacob-an** [LUXROBO/pyMODI#103]
* pyMODI version:0.7.0
* Python version:3.7
* Operating System:Windows 10

### Description
Calling "display.set_text('Hello')" raises an TypeError stating that a given json is not serializable.

### What I Expected
The text 'Hello' should be printed on the display module, and it should not throw an error.

**Comment by jha929** [comment]
Please attach a relevant python script for reproducing the issue.

**Comment by jha929** [comment]
I've managed to reproduce your issue and it has been fixed now.
