### ISSUE TITLE
IR module returns opposite distance value

### ISSUE THREAD

**Issue by dajeong012** [LUXROBO/pyMODI#115]
* pyMODI version: 0.7.2
* Python version: 3.7.4
* Operating System: macOS Catalina 10.15.3

### Description

"ir.get_distance()" returns greater value when object gets closer.

### What I Did

`	if ir.get_distance() > 30:
		led.set_on()`

### What I Expected
Returned distance value should be less when object gets closer.

**Comment by jha929** [comment]
Thanks for reporting the issue.

The function has now been renamed to get_proximity for clarity and will be updated in the next version, 0.7.2.
