### ISSUE TITLE
Processes is not being terminated properly

### ISSUE THREAD

**Issue by funkywoong** [LUXROBO/pymodi#133]
* pyMODI version: 0.7.1 / develop
* Python version: 3.7.5
* Operating System: Windows 10

### Description

When I executed pyMODI in Windows 10 OS, the script wasn't terminated properly.
I just thought this might occur because of problem related in multiprocessing module. 
I confirmed that a process named 'self.__task' have already been stopped before the script over. 
I attached the error messages.

```
(modi_ai) C:\Users\funkywoong\Desktop\MODI_AI\temp> python test.py
Start initializing connected MODI modules
MODI modules are initialized!
DONE
Exception ignored in: <function SerTask.__del__ at 0x0000019AD1DA0E58>
Traceback (most recent call last):
  File "C:\Users\funkywoong\AppData\Local\Continuum\anaconda3\envs\modi_ai\lib\modi\_ser_task.py", line 21, in __del__
  File "C:\Users\funkywoong\AppData\Local\Continuum\anaconda3\envs\modi_ai\lib\modi\_ser_task.py", line 51, in _close_conn
AttributeError: 'NoneType' object has no attribute 'close'
```
### What I Did
Deleted '\_\_del\_\_()' magic method of 'ser_task.py' to prevent calling close() method.

**Comment by k2sebeom** [comment]
Download a new version of pymodi 0.9.0. We terminate each process manually.
