### ISSUE TITLE
Code blocks not showing on Read the Docs site

### ISSUE THREAD

**Issue by drecali** [LUXROBO/pymodi#266]
### Issue Description
Some pages of the PyMODI Read the Docs site are missing code blocks. The problem is only on Read the Docs. I checked the same pages on GitHub and the code blocks were displayed identically for all 4 pages. There is some difference in how the code blocks are implemented in each file, so when the .rst files are generated, some of those code blocks are lost in the process. 

#### Read the Docs - Missing code blocks:
https://pymodi.readthedocs.io/en/master/readme.html
https://pymodi.readthedocs.io/en/master/contributing.html

#### Read the Docs - OK code blocks
https://pymodi.readthedocs.io/en/master/usage.html
https://pymodi.readthedocs.io/en/master/installation.html

### System Info
Read the Docs website, GitHub website

You can obtain the pymodi version with:\
python -c "import modi; print(modi.\_\_version__)"

You can obtain the Python version with:\
python --version

### Additional Context

**Comment by jha929** [comment]
Hi, thanks for raising the issue. We will take a look at it ASAP :)

I will let you know if there is any update on this.

**Comment by k2sebeom** [comment]
https://pymodi.readthedocs.io/en/develop/readme.html
https://pymodi.readthedocs.io/en/develop/contributing.html

Code blocks in readme and contribution are now showing properly.
Thanks for your contribution to pymodi.
